In [ ]:
import numpy as np
from numpy.linalg import eigh, norm

In [ ]:
A=np.array([[-5, 2, 3], [2, 5, 1], [-3, 1, -5]])

In [ ]:
A.T@A

array([[38, -3,  2],
       [-3, 30,  6],
       [ 2,  6, 35]])

In [ ]:
eigh(A.T@A)

(array([25., 39., 39.]), array([[ 0.26726124, -0.96362411,  0.        ],
        [ 0.80178373,  0.22237479,  0.5547002 ],
        [-0.53452248, -0.14824986,  0.83205029]]))

In [ ]:
ev, V =eigh(A.T@A)

In [ ]:
V

array([[ 0.26726124, -0.96362411,  0.        ],
       [ 0.80178373,  0.22237479,  0.5547002 ],
       [-0.53452248, -0.14824986,  0.83205029]])

In [ ]:
V[0]

array([ 0.26726124, -0.96362411,  0.        ])

In [ ]:
V[:,0]

array([ 0.26726124,  0.80178373, -0.53452248])

In [ ]:
u0= A@V[:,0]/norm(A@V[:,0])
u1= A@V[:,1]/norm(A@V[:,1])
u2= A@V[:,2]/norm(A@V[:,2])

In [ ]:
U=np.array([u0,u1,u2]).T

In [ ]:
U.T@A@V

array([[ 5.00000000e+00,  4.61927558e-17, -5.80878766e-17],
       [-3.24483433e-16,  6.24499800e+00,  1.06687423e-16],
       [-2.24630037e-16, -1.28454465e-17,  6.24499800e+00]])

In [ ]:
np.round(U.T@A@V, decimals=5)

array([[ 5.   ,  0.   , -0.   ],
       [-0.   ,  6.245,  0.   ],
       [-0.   , -0.   ,  6.245]])

In [ ]:
#A = U@D@V.T is the SVD